### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by janokary** [Ryuske/wepay-laravel#2]
Hi, is there gonna be an update for laravel5.1lts ?

**Comment by Ryuske** [comment]
Eventually, yes. Eventually I'll be migrating the system I'm using it on to Laravel 5.1, but it might be a while. If you want to do a pull request that would be awesome.

**Comment by girirajsinh9030** [comment]
i have try to install this package ni laravel 5.6 it's display below error
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Conclusion: remove laravel/framework v5.6.39
- Conclusion: don't install laravel/framework v5.6.39
- Conclusion: don't install laravel/framework v5.6.38
- Conclusion: don't install laravel/framework v5.6.37
- Conclusion: don't install laravel/framework v5.6.36
- Conclusion: don't install laravel/framework v5.6.35
- Conclusion: don't install laravel/framework v5.6.34
- Conclusion: don't install laravel/framework v5.6.33
- Conclusion: don't install laravel/framework v5.6.32
- Conclusion: don't install laravel/framework v5.6.31
- Conclusion: don't install laravel/framework v5.6.30
- Conclusion: don't install laravel/framework v5.6.29
- Conclusion: don't install laravel/framework v5.6.28
- Conclusion: don't install laravel/framework v5.6.27
- Conclusion: don't install laravel/framework v5.6.26
- Conclusion: don't install laravel/framework v5.6.25
- Conclusion: don't install laravel/framework v5.6.24
- Conclusion: don't install laravel/framework v5.6.23
- Conclusion: don't install laravel/framework v5.6.22
- Conclusion: don't install laravel/framework v5.6.21
- Conclusion: don't install laravel/framework v5.6.20
- Conclusion: don't install laravel/framework v5.6.19
- Conclusion: don't install laravel/framework v5.6.18
- Conclusion: don't install laravel/framework v5.6.17
- Conclusion: don't install laravel/framework v5.6.16
- Conclusion: don't install laravel/framework v5.6.15
- Conclusion: don't install laravel/framework v5.6.14
- Conclusion: don't install laravel/framework v5.6.13
- Conclusion: don't install laravel/framework v5.6.12
- Conclusion: don't install laravel/framework v5.6.11
- Conclusion: don't install laravel/framework v5.6.10
- Conclusion: don't install laravel/framework v5.6.9
- Conclusion: don't install laravel/framework v5.6.8
- Conclusion: don't install laravel/framework v5.6.7
- Conclusion: don't install laravel/framework v5.6.6
- Conclusion: don't install laravel/framework v5.6.5
- Conclusion: don't install laravel/framework v5.6.4
- Conclusion: don't install laravel/framework v5.6.3
- Conclusion: don't install laravel/framework v5.6.2
- Installation request for ryuske/wepay-laravel dev-master -> satisfiable by ryuske/wepay-laravel[dev-master].
- Conclusion: don't install laravel/framework v5.6.1
- Conclusion: don't install laravel/framework v5.6.0
- ryuske/wepay-laravel dev-master requires illuminate/support 4.2.* -> satisfiable by illuminate/support[4.2.x-dev, v4.2.0-BETA1, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
- don't install illuminate/support 4.2.x-dev|don't install laravel/framework 5.6.x-dev
- don't install illuminate/support v4.2.0-BETA1|don't install laravel/framework 5.6.x-dev
- don't install illuminate/support v4.2.1|don't install laravel/framework 5.6.x-dev
- don't install illuminate/support v4.2.12|don't install laravel/framework 5.6.x-dev
- don't install illuminate/support v4.2.16|don't install laravel/framework 5.6.x-dev
- don't install illuminate/support v4.2.17|don't install laravel/framework 5.6.x-dev
- don't install illuminate/support v4.2.2|don't install laravel/framework 5.6.x-dev
- don't install illuminate/support v4.2.3|don't install laravel/framework 5.6.x-dev
- don't install illuminate/support v4.2.4|don't install laravel/framework 5.6.x-dev
- don't install illuminate/support v4.2.5|don't install laravel/framework 5.6.x-dev
- don't install illuminate/support v4.2.6|don't install laravel/framework 5.6.x-dev
- don't install illuminate/support v4.2.7|don't install laravel/framework 5.6.x-dev
- don't install illuminate/support v4.2.8|don't install laravel/framework 5.6.x-dev
- don't install illuminate/support v4.2.9|don't install laravel/framework 5.6.x-dev
- Installation request for laravel/framework 5.6.* -> satisfiable by laravel/framework[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].

**Comment by Ryuske** [comment]
Unfortunately this was built for Laravel 4.2, and won't work with Laravel 5+. I don't have any plans at the moment to upgrade it to start working with the latest versions again.
